language: go
go:
- 1.2
- tip
notifications:
  slack:
    secure: BBtX6Qg8Dp63u6sfcEK7xeqBAL8ok/RI7b47zBEfWI/HYkMAyF+cqc0PobgIoVelfoUNDZVxV20hoLIeE9GpI0ifcfS61LLU+Mx0Kt9Zczu31oEmZR0wGosxvfi0abnFVsmsxvZ+PqtTgy7JlqTgAguLQFwDY0lun77sGLld9DVE0UFhHThXuj5CeatvX7z7bxR8fqdHwFxO5gLgPWNoNmFScGI8+CcXH4J7QRs8Coos6sPYvflFO8t8tSeDYXZ3RYBh5UxEDjIsRkSfSvWqCq2BBEmLTJcsJ9lxzF6nTloXujO3uDSomwHD9j1qJAuFzKaUjFoBmJqAWm+Yt6fhiPeQkxukllWtBaaXk70msbxcrlEh5IfnDrpzd+hSCrDJoLj6hReV5ga5cVicNuxLIYVs0ELtB5yKhh+3e/VJMr6vNFGrw6otHBX4PdoRk7aEOyQ9fLI0o1nmyiWoxU8wx2JKUsj0Ze8xW7puJbPdVTJyncw3J0iMcYUtNdQN+8+Jyqk6yMm5Di/Is0dBzYW45w9AW/ZOhjQ037erTk2SpAIK01xElIKbsiFt2bSBmZwGpI0zT34W5IHEZCRJyQD/c9d2Gs2lGcH9YjAxLDhEH48zyqRV6nO4J6uZM3BhIzBwiOUPeoikJoLXIh+Dd96iFYGWMigaV99muO/N4rl1pho=
